name: Signup Issue Automation

on:
  issues:
    types: [opened, closed, edited]

permissions:
  contents: write
  issues: write

concurrency:
  group: hackathon-automation-global
  cancel-in-progress: false

jobs:
  process-signup:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'opened' && startsWith(github.event.issue.title, 'Registration')) ||
      (github.event.action == 'closed' && github.event.issue.state_reason == 'completed' && startsWith(github.event.issue.title, 'Registration') && github.actor != 'github-actions[bot]') ||
      (github.event.action == 'edited' && startsWith(github.event.issue.title, 'Registration'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Signup Info, Create Registration File and Update Table
        id: extract-signup
        # 关键：允许步骤失败后继续执行后续步骤（否则错误处理步骤会被跳过）
        continue-on-error: true
        run: |
          # 捕获脚本输出和错误信息
          if node materials/scripts/signup_extract.js 2>&1 | tee script_output.log; then
            # 脚本执行成功：设置成功状态
            echo "script_success=true" >> $GITHUB_OUTPUT
            echo "✅ 脚本执行成功"
          else
            # 脚本执行失败：设置失败状态+提取错误信息
            echo "script_success=false" >> $GITHUB_OUTPUT
            if grep -q "ERROR_MESSAGE:" script_output.log; then
              ERROR_MSG=$(grep "ERROR_MESSAGE:" script_output.log | sed 's/ERROR_MESSAGE: //')
              echo "error_message=$ERROR_MSG" >> $GITHUB_OUTPUT
            else
              echo "error_message=❌ **处理失败**\n\n处理过程中发生未知错误，请检查提交格式是否正确。" >> $GITHUB_OUTPUT
            fi
            echo "❌ 脚本执行失败"
            # 移除 exit 1：避免提前终止步骤，确保输出变量能正常写入
          fi
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_USER: ${{ github.event.issue.user.login }}
          GITHUB_OUTPUT: ${{ github.output }}

      - name: Handle Script Errors
        # 关键：仅当 extract-signup 步骤输出的 script_success 为 false 时执行
        if: steps.extract-signup.outputs.script_success == 'false'
        # 移除错误的 needs 字段！同一个 Job 内步骤默认按顺序执行，无需 needs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            // 从 extract-signup 步骤的输出中获取错误信息（若未获取到则用默认值）
            const errorMessage = steps.extract-signup.outputs.error_message || '❌ **处理失败**\n\n处理过程中发生未知错误，请检查提交格式是否正确。';
            
            // 向 Issue 中添加错误评论
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: errorMessage
            });
            
            console.log(`❌ 错误已通过评论告知用户: Issue #${issue_number}`);
            // 标记整个作业为失败（符合错误场景的预期状态）
            core.setFailed(errorMessage);

      - name: Commit & Push Changes
        # 仅当脚本执行成功时才提交代码
        if: steps.extract-signup.outputs.script_success == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 拉取最新代码，但保留本地更改
          git fetch origin main
          git merge origin/main --no-edit || true
          
          git add .
          # 仅当有变更时才提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add registration for ${{ github.event.issue.user.login }}"
            git push origin HEAD:main
            echo "✅ 注册信息已成功提交"
          fi

      - name: Comment and close issue
        # 仅当脚本执行成功时才添加成功评论并关闭 Issue
        if: steps.extract-signup.outputs.script_success == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            const user = context.payload.issue.user.login;

            try {
              // 根据触发动作设置评论中的类型（Auto/Edit/Manual）
              let actionType = 'Manual';
              if (context.payload.action === 'opened') actionType = 'Auto';
              else if (context.payload.action === 'edited') actionType = 'Edit';
              
              // 添加成功评论
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `✅ Registration processed successfully! (${actionType})`
              });
              
              // 自动触发或编辑时关闭 Issue
              if (context.payload.action === 'opened' || context.payload.action === 'edited') {
                await github.rest.issues.update({
                  owner,
                  repo,
                  issue_number,
                  state: 'closed',
                  state_reason: 'completed'
                });
              }
              
              console.log(`✅ Issue #${issue_number} processed and closed successfully`);
            } catch (error) {
              console.error(`Error processing issue: ${error.message}`);
              core.setFailed(`Error processing issue: ${error.message}`);
            }